name: Deploy

on:
  schedule:
    - cron: '2 * * * *'
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge main on aux-branch
        run: |-
          git config --global user.email "jartigag@pm.me"
          git config --global user.name "jartigag"
          git fetch origin aux-branch:aux-branch
          git merge --allow-unrelated-histories -s ours aux-branch
          git switch aux-branch
          git merge --no-ff --no-commit main
          git commit -m "Merge branch 'aux-branch'"
      - name: Run translator
        run: |
          ./translator.py
      - name: Commit, push and merge if changed
        run: |-
          git diff
          git config --global user.email "jartigag@pm.me"
          git config --global user.name "jartigag"
          git add -A
          git commit -m "." || exit 0
          git push origin aux-branch
          git switch main
          git merge aux-branch
          git push

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
